public without sharing class OpportunityService {
    public List<String> getOfficeList() {
        return null;
    }

    public void syncToStaffingRequest(Id id, String str) {

    }

    public Integer getStaffingRequestCount(Id id) {
        return 0;
    }

    public Boolean getPartnershipEditAccess(Id id, Id id) {
        return true;
    }

    public List<Opportunity> getOpenedOpportunitiesBasicWithOwnerIds(List<Id> ids) {
        return null
                ;
    }

    public List<Opportunity> getOpportunitiesWithOwnerIdsExceptClosedLost(List<Id> ids) {
        return null;
    }

    public Map<String, Map<String, List<Opportunity>>> getGroupedThisYearOpportunitiesByOwnerIds(List<Id> ids) {
        return null;
    }

}
